const LOADING = {
  LOADING: "LOADING",
  SHOW: "LOADING_SHOW",
  HIDE: "LOADING_HIDE",
};

const SYNC_APP = {
  REQUEST: "SYNC_APP_REQUEST",
  SUCCESS: "SYNC_APP_SUCCESS",
  FAILURE: "SYNC_APP_FAILURE",
};

const SIGN_OUT = "SIGN_OUT";
const SIGN_IN = {
  REQUEST: "SIGN_IN_REQUEST",
  SUCCESS: "SIGN_IN_SUCCESS",
  FAILURE: "SIGN_IN_FAILURE",
};

const ACCOUNT = {
  AUTHENTICATION: "ACCOUNT_AUTHENTICATION",
  SIGN_OUT: "ACCOUNT_SIGN_OUT",
  ACCOUNT_INFO: "DATA_ACCOUNT_INFO",
};


const SYNC_APP_SUCCESS = "SYNC_APP_SUCCESS";
const ACTION_BOOK_TYPE = "ACTION_BOOK_TYPE";
const SAVE_MAKE_APPOINT_DATA = "SAVE_MAKE_APPOINT_DATA";
const RESET_MAKE_APPOINT_DATA = "RESET_MAKE_APPOINT_DATA";
const SAVE_HEATH_FACILITIES_DATA = "SAVE_HEATH_FACILITIES_DATA"; // danh sach co so y te
const MEDICEL_SPECIALIZATION_DATA = "MEDICEL_SPECIALIZATION_DATA"; // danh sach Chuyen khoa cua co so y te
const RESPONSE_PATIENT_RECORDS = "RESPONSE_PATIENT_RECORDS"; // danh sach ho so y te
const RESPONSE_SEARCH_PATIENT_RECORDS = "RESPONSE_SEARCH_PATIENT_RECORDS"; // ket qua tim kiem ho so
export const RESPONSE_GET_NOTIFICATIONS = "RESPONSE_GET_NOTIFICATIONS"; // ket qua tim kiem ho so
export const RESPONSE_COUNT_NOTI_UNREAD = "RESPONSE_COUNT_NOTI_UNREAD"; // số thông báo chưa đọc
export const RESPONSE_GET_FEEDBACKS = "RESPONSE_GET_FEEDBACKS"; // ket qua gop y
export const RESPONSE_GET_FEEDBACKS_RESET = "RESPONSE_GET_FEEDBACKS_RESET"; // ket qua gop y
export const RESPONSE_GET_TOPICS = "RESPONSE_GET_TOPICS"; // ket qua gop y
export const MEDICEL_PROCESS_FEEDBACK_DATA = "MEDICEL_PROCESS_FEEDBACK_DATA"; // ket qua gop y
//responseHeathFaclitiesSearch
export const RESPONSE_HEATH_FACLITIES_SEARCH = "RESPONSE_HEATH_FACLITIES_SEARCH"; // Tra cứu cơ sở Y Tế
export const RESPONSE_HEATH_FACLITIES_SEARCH_LOAD_MODE = "RESPONSE_HEATH_FACLITIES_SEARCH_LOAD_MODE"; // Tra cứu cơ sở Y Tế
export const RESPONSE_HEATH_FACLITIES_SEARCH_LOAD_MODE_RESET = "RESPONSE_HEATH_FACLITIES_SEARCH_LOAD_MODE_RESET"; // Tra cứu cơ sở Y Tế
//bác sỹ
export const RESPONSE_GET_DOCTOR = "RESPONSE_GET_DOCTOR"; //
export const RESPONSE_GET_DOCTOR_RESET = "RESPONSE_GET_DOCTOR_RESET"; //

const GET_INFO_DOCTOR = "GET_INFO_DOCTOR";
const RESPONSE_HEALTH_QUESTION_LIST = "RESPONSE_HEALTH_QUESTION_LIST";
const RESPONSE_HEALTH_DECLARATION_LIST = "RESPONSE_HEALTH_DECLARATION_LIST";

export {
  LOADING,
  SYNC_APP,
  SIGN_IN,
  SIGN_OUT,
  ///
  SYNC_APP_SUCCESS,
  ACTION_BOOK_TYPE,
  ACCOUNT,
  SAVE_MAKE_APPOINT_DATA,
  RESET_MAKE_APPOINT_DATA,
  SAVE_HEATH_FACILITIES_DATA,
  RESPONSE_SEARCH_PATIENT_RECORDS,
  RESPONSE_PATIENT_RECORDS,
  MEDICEL_SPECIALIZATION_DATA,
  // RESPONSE_INSURANCE_CODES,
  //
  GET_INFO_DOCTOR,
  RESPONSE_HEALTH_QUESTION_LIST,
  RESPONSE_HEALTH_DECLARATION_LIST
};
