export const COLOR_BROWN = '#693013';
export const COLOR_BLACK = '#2A2A2A';
export const COLOR_GRAY = '#7D7D7D';
export const COLOR_BORDER = '#707070';
export const COLOR_WHITE = '#FFFFFF';
export const COLOR_GRAY_LIGHT = '#F2F2F2';
export const COLOR_RED_LIGHT = '#D94343';
export const COLOR_RED = '#FF0000';
export const COLOR_GREEN = '#56AF45';
export const COLOR_VIOLET = '#c730c7';
export const COLOR_BLUE = '#454F97';
export const COLOR_BLUE_LIGHT = '#1055CC';
export const COLOR_BLUE_APP = '#C9DAF8';
export const COLOR_ORANGE = '#EC7105';
export const COLOR_YELLOW = '#F6AA00';
export const COLOR_YELLOW_LIGHT = '#FCEEA1';
export const COLOR_GRAY_300 = '#E0E0E0';
export const COLOR_GREEN_LIGHT = '#56AF4520';
const COLOR_TEXT = COLOR_BLACK;

const COLOR_TEXT_BUTTON_TYPE_1 = COLOR_WHITE;
const COLOR_BORDER_BUTTON_TYPE_1 = COLOR_ORANGE;

const COLOR_TEXT_BUTTON_TYPE_2 = COLOR_ORANGE;
const COLOR_BORDER_BUTTON_TYPE_2 = COLOR_ORANGE;

const COLOR_TEXT_TAB_BAR_ACTIVE = COLOR_WHITE;
const COLOR_BORDER_TAB_BAR_ACTIVE = COLOR_ORANGE;

const COLOR_TEXT_TAB_BAR_UN_ACTIVE = COLOR_ORANGE;
const COLOR_BORDER_TAB_BAR_UN_ACTIVE = COLOR_ORANGE;

export const APP_COLOR = {
  COLOR_TEXT,
  COLOR_TEXT_BUTTON_TYPE_1,
  COLOR_BORDER_BUTTON_TYPE_1,
  COLOR_TEXT_BUTTON_TYPE_2,
  COLOR_BORDER_BUTTON_TYPE_2,
  COLOR_TEXT_TAB_BAR_ACTIVE,
  COLOR_BORDER_TAB_BAR_ACTIVE,
  COLOR_TEXT_TAB_BAR_UN_ACTIVE,
  COLOR_BORDER_TAB_BAR_UN_ACTIVE
};
