import {StyleSheet} from 'react-native';
import {Color, Dimension, Font} from '../../commons/constants';
import {ratioW} from '../../commons/utils/devices';
const widthTitle = 88;
export default StyleSheet.create({
  styleContains: {
    backgroundColor: 'white',
    padding: Dimension.padding10,
    borderRadius: 8,
    marginHorizontal: Dimension.margin,
    marginVertical: Dimension.margin5,
    elevation: 2,
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowColor: '#000000',
    position: 'relative',
  },

  styleIconItem: {
    marginHorizontal: Dimension.margin5,
    backgroundColor: Color.White,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    width: 40,
  },
  viewSTT: {
    borderColor: Color.border,
    borderWidth: 0.5,
    borderRadius: 30,
    position: 'absolute',
    left: -5,
    top: -5,
    backgroundColor: 'white',
    overflow: 'hidden',
    alignContent: 'center',
  },
  textSTT: {
    color: Color.Supernova,
    fontWeight: '700',
    padding: 5,
    textAlign: 'center',
    minWidth: 30,
    minHeight: 30,
    backgroundColor: 'white',
    overflow: 'hidden',
  },

  styleImageTelco: {
    width: widthTitle,
    height: 40,
    alignSelf: 'center',
    marginRight: Dimension.margin15,
    resizeMode: 'stretch',
  },
  styleImageTelcoCircle: {
    width: 40,
    height: 40,
    alignSelf: 'center',
    marginRight: Dimension.margin15,
    resizeMode: 'center',
    borderRadius: 100,
    borderColor: Color.MayaBlue,
    borderWidth: 0.5,
    padding: 3,
  },
  styleContainHead: {flex: 1},
  styleContainRow: {},
  styleTextSim: {
    marginBottom: 5,
    color: Color.MayaBlue,
    fontSize: Dimension.fontSize16,
    fontWeight: '700',
  },
  styleContainerText: {
    flex: 1,
    flexDirection: 'row',
    // backgroundColor: '#345',
  },
  styleTextTitle: {
    marginRight: Dimension.margin10,
    fontSize: Dimension.fontSize16 * ratioW,
    width: widthTitle,
    alignSelf: 'center',
    alignContent: 'flex-start',
    fontStyle: 'normal',
    fontFamily: Font.FiraSansRegular,
  },

  styleValueStatus: {
    fontSize: Dimension.fontSize15,
    fontWeight: '700',
    color: Color.colorText,
    fontFamily: Font.FiraSansRegular,
  },
  styleValue: {
    fontSize: Dimension.fontSize15,
    fontWeight: '600',
    color: Color.colorText,
    fontFamily: Font.FiraSansRegular,
  },
  styleOrderValue: {
    flex: 1,
    fontSize: Dimension.fontSize15,
    alignSelf: 'center',
    fontWeight: '700',
    color: Color.Indigo,
  },
  styleStauts: {
    color: Color.WildWatermelon,
    padding: Dimension.padding5,
    height: 30,
    borderRadius: 4,
    fontWeight: '700',
    fontFamily: Font.FiraSansRegular,
  },
  /////OrderDetail
  styleContainOrderInfo: {
    width: '100%',
    backgroundColor: 'white',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    elevation: 20,
  },
  styleContainBlock: {
    margin: Dimension.margin,
    paddingHorizontal: Dimension.padding15,
    paddingBottom: Dimension.padding5,
    marginTop: Dimension.margin25,
    minHeight: 50,
    borderColor: Color.star,
    borderWidth: Dimension.borderWidth,
    borderRadius: Dimension.borderRadius,
    backgroundColor: 'white',
  },
  styleBlockTitle: {
    height: 30,
    paddingHorizontal: Dimension.padding,
    borderColor: Color.star,
    borderWidth: Dimension.borderWidth,
    borderRadius: Dimension.borderRadius4,
    position: 'absolute',
    left: 10,
    top: -15,
    backgroundColor: Color.star,
    textAlign: 'center',
    justifyContent: 'center',
    textAlignVertical: 'center',
    fontSize: Dimension.fontSize14,
    fontWeight: '700',
    color: 'white',
    paddingVertical: 5,
    overflow: 'hidden',
  },

  styleTitle: {
    marginRight: Dimension.margin15,
    fontSize: Dimension.fontSize16 * ratioW,
    width: widthTitle,
    alignSelf: 'center',
    alignContent: 'flex-start',
    fontStyle: 'normal',
    fontFamily: Font.FiraSansRegular,
  },

  styleTextValue: {
    fontSize: Dimension.fontSize15,
    alignSelf: 'center',
    fontWeight: '700',
    color: Color.darkRedIOS,
  },
  styleContainTextPackage: {
    // justifyContent: 'center',
    alignItems: 'center',
  },

  styleTextValueDetail: {
    fontSize: Dimension.fontSize13,
    alignSelf: 'center',
    // textAlign: 'right',
    fontWeight: '700',
    color: Color.colorText,
    fontFamily: Font.FiraSansRegular,
    // flexWrap: 'wrap',
    flex: 1,
  },
  styleContainBlockCart: {
    paddingBottom: Dimension.padding5,
    marginTop: Dimension.margin25,
    minHeight: 50,
    borderColor: Color.star,
    borderWidth: Dimension.borderWidth,
    borderRadius: Dimension.borderRadius,
    backgroundColor: 'white',
  },
  styleViewButton: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 5,
  },

  styleButtomActionAccept: {
    // width: 85,
    marginLeft: Dimension.margin5,
    borderWidth: 0.5,
    borderColor: Color.PersianGreen,
    padding: Dimension.padding5,
    borderRadius: 4,
  },

  styleButtomActionCancel: {
    // width: 85,
    borderWidth: 0.5,
    borderColor: Color.WildWatermelon,
    padding: Dimension.padding5,
    borderRadius: 4,
  },

  styleTextButton: {
    marginLeft: 5,
  },

  textButton: {
    color: Color.WildWatermelon,
    fontWeight: '700',
    fontFamily: Font.FiraSansRegular,
  },

  styleViewButtonFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 20,
    borderTopColor: Color.border,
    borderTopWidth: 1,
  },

  styleButtonCancelCart: {
    flex: 1,
    marginVertical: Dimension.margin10,
    backgroundColor: Color.Border,
  },
  stTextStatus: {
    height: 25,
    borderBottomWidth: 1,
  },
  styleIconStatus: {
    // backgroundColor: '#345',
  },
  stContainsTextStatus: {
    alignContent: 'center',
    justifyContent: 'center',
  },
  textStatus: {
    marginLeft: 5,
    fontSize: Dimension.fontSize12,
    alignSelf: 'center',
    fontWeight: '700',
  },

  styleHightlightCard: {
    backgroundColor: 'white',
    shadowOpacity: 0.25,
    shadowRadius: 2,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowColor: '#000000',
    elevation: 20,
    zIndex: 9999,
  },
  stylesContainSearch: {
    marginBottom: 12,
  },
  styleInputSearch: {
    // borderRadius: 40,
    borderColor: Color.Border,
    borderWidth: 1,
    borderRadius: 40,
    // backgroundColor: '#fff',
  },
  inputContainer: {
    position: 'relative',
    paddingHorizontal: 10,
    paddingVertical: 10,
    height: 59,
    overflow: 'hidden',
  },
  uploadContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  customeUploadButton: {
    borderRadius: 10,
    borderColor: '#ccc',
    borderStyle: 'solid',
    borderWidth: 1,
    paddingHorizontal: 35,
    paddingVertical: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  customeUploadButtonText: {
    color: '#38C8EC',
    fontSize: 14,
    fontStyle: 'italic',
    marginRight: 5,
  },
  stContainButton: {
    height: 120,
    width: 120,
    backgroundColor: '#345',
  },
  stContainAlbum: {},
});
