require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'simthanhdat' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

   # Cấu hình Permission:
   permissions_path = '../node_modules/react-native-permissions/ios'
   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  # pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  

  pod 'RealmJS', :path => '../node_modules/realm'
#  pod 'Firebase/Analytics'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  # pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

 target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.14.3', '<= 3.9.0'
  end
   
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
           config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
         end
       end
  end
  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     if target.name == "React"
  #       target.remove_from_project
  #     end
  
  #     # It removes React & Yoga from the Pods project, as it is already included in the main project.
  #     targets_to_ignore = %w(React yoga)
  #     if targets_to_ignore.include? target.name
  #       target.remove_from_project
  #     end
  #   end
end

