const LOADING = {
  LOADING: 'LOADING',
  SHOW: 'LOADING_SHOW',
  HIDE: 'LOADING_HIDE',
};

const SYNC_APP = {
  REQUEST: 'SYNC_APP_REQUEST',
  SUCCESS: 'SYNC_APP_SUCCESS',
  FAILURE: 'SYNC_APP_FAILURE',
};
const SIGN_OUT = 'SIGN_OUT';
const SIGN_IN = {
  REQUEST: 'SIGN_IN_REQUEST',
  SUCCESS: 'SIGN_IN_SUCCESS',
  FAILURE: 'SIGN_IN_FAILURE',
};

const GET_ACCOUNT_INFO = {
  SUCCESS: 'ACCOUNT_INFO_SUCCESS',
  FAILURE: 'ACCOUNT_INFO_FAILURE',
};

const SIM_CATEGORIES = {
  REQUEST: 'SIM_CATEGORIES_REQUEST',
  SAVE: 'SIM_CATEGORIES_SAVE',
  FAILURE: 'SIM_CATEGORIES_FAILURE',
};

const SIM_SEARCH = {
  REQUEST: 'SIM_SEARCH_REQUEST',
  RESPONSE: 'SIM_SEARCH_RESPONSE',
  FAILURE: 'SIM_SEARCH_FAILURE',
};

const RESET_SEARCH_SIM = 'RESET_SEARCH_SIM';

const SIM_COPY = {
  COPY: 'SIM_COPY',
  RESET: 'SIM_COPY_RESET',
};

const MY_ORDER_BY_STATUS = {
  RESPONSE: 'MY_ORDER_BY_STATUS_RESPONSE',
  FAILURE: 'MY_ORDER_BY_STATUS_FAILURE',
};

const CREATED_NEW_CART = {
  RESPONSE: 'CREATED_NEW_CART_RESPONSE',
  FAILURE: 'CREATED_NEW_CART_FAILURE',
};

const SAVE_PROVINCES = 'SAVE_PROVINCES';
const SAVE_DISTRICTS = 'SAVE_DISTRICTS';
const SAVE_WARDS = 'SAVE_WARDS';

const RESPONSE_GET_NOTIFICATIONS = 'RESPONSE_GET_NOTIFICATIONS';
const RESPONSE_READED_NOTIFI = 'RESPONSE_READED_NOTIFI';
const DATA_NOTIFICAITON = 'DATA_NOTIFICAITON';
const RESPONSE_READED_ALL_NOTIFI = 'RESPONSE_READED_ALL_NOTIFI';
const SET_TOTAL_NOTIFI_UNREAD = 'SET_TOTAL_NOTIFI_UNREAD';

export {
  LOADING,
  SYNC_APP,
  SIGN_IN,
  SIGN_OUT,
  GET_ACCOUNT_INFO,
  SIM_CATEGORIES,
  SIM_SEARCH,
  SIM_COPY,
  MY_ORDER_BY_STATUS,
  RESET_SEARCH_SIM,
  CREATED_NEW_CART,
  SAVE_PROVINCES,
  SAVE_DISTRICTS,
  SAVE_WARDS,
  RESPONSE_GET_NOTIFICATIONS,
  RESPONSE_READED_NOTIFI,
  DATA_NOTIFICAITON,
  RESPONSE_READED_ALL_NOTIFI,
  SET_TOTAL_NOTIFI_UNREAD,
};
