export default Object.freeze({
  file: "file",
  avatar: "avatar",
  name: "name",
  Gender: "gender",
  GenderName: "genderName",
  healthInsuranceCode: "healthInsuranceCode",
  height: "height",
  weight: "weight",
  address: "address",
  phone: "phone",
  email: "email",
  userId: "userId",
  AREA: "AREA",
  AreaFullName: "AreaFullName",
  cityCode: "cityCode",
  districtCode: "districtCode",
  wardCode: "wardCode",
  relationship: "relationship",
  RelationshipName: "relationshipName",
  dob: "dob",
});
