export const STRING = {
  history_of_using_coupons: 'クーポン利用履歴',
  code_coupon: 'コード',
  term_if_use: '利用規約',
  contact_to_company: '会社概要',
  login: 'ログイン',
  log_out: 'ログアウト',
  register: '会員登録',
  end_of_login_session_please_log_in_again:
    'セッションの有効期限が切れています。再度ログインを行なってください。',
  wrong_phone_or_pass: '認証情報が正しくありません。',
  are_you_sure_you_want_to_sign_out_of_the_app:
    'ログアウトします。よろしいですか？',
  cancel: 'キャンセル',
  ok: 'OK',
  email: 'メールアドレス',
  password: 'パスワード',
  forgot_password: 'パスワードを忘れた場合',
  do_not_have_an_account: ' 新規会員登録はこちら',
  register_now: 'こちら',
  see_more: 'もっとみる',
  send: '送信',
  send_confirmation_successful: '認証コードを送信しました。',
  we_have_sent_a_confirmation_code_to_your_registration_email_please:
    '新しいパスワードと受信された認証コードを入力してください。',
  error_password_validation: 'パスワードは半角英字・数字を含む必要があります。',
  error_password_confirm: '同じ値をもう一度入力してください。',
  code: 'メール送信済み認証コード',
  error_not_type_email: '有効なEメールアドレスを入力してください。',
  name: '氏名',
  email_already_exits: '既にご登録済みのメールアドレスです。',
  email_not_already_exits: '存在しないメールアドレスです。',
  an_error_occurred: '接続エラー',
  please_try_again_later:
    'ただいま大変混み合っております。しばらく経ってから再度お試しください。',
  sign_up_success: '認証メールを送信しました。',
  please_check_email_and_confirm_account:
    'まだ登録は完了しておりません。ご登録のメールアドレスからアカウント認証を完了してください。',
  notification: 'お知らせ',
  push_notification: 'PUSH通知',
  notification_important: '重要なお知らせ',
  network_error_try_again_later:
    'ネットワークに接続できませんでした。後でやり直してください。',
  catalog_near_you: '近くのチラシ',
  my_bookmark: 'お気に入り',
  menu_is_un_active: '該当の機能はありません。',
  are_you_sure_you_want_to_use_coupon: 'このクーポンを使用しますか。',
  use_now: 'クーポン利用する',
  used: '使用済み',
  update_app: '更新する',
  detail: 'クーポン詳細',
  search: '検索',
  store_near_you: '近くのお店',
  search_stores: '店舗検索',
  category: '都道府県別',
  phone: '住所',
  phone_is_use: 'この電話番号はシステムに既存しました。',
  or_adress: '電話番号など',
  all: 'すべて',
  member_only: '会員限定',
  shop_only: '店舗限定',
  store: '店舗検索',
  video: '動画',
  catalog: 'チラシ',
  setting: '設定',
  coupon: 'クーポン',
  go_back: '戻る',
  agree_start_now: '同意してアプリを始める',
  skipp: 'スキップ',
  title: 'タイトル',
  the_name_must_be_at_least_two_characters_long: '会員登録',
  wrong_password: 'パスワードが正しくありません。',
  wrong_password_or_email: 'アカウントまたはパスワードが間違っております。',
  change_your_new_password_successfully: 'パスワードを更新しました。',
  new_password_change_failed:
    'パスワードを更新できませんでした。後でやり直してください。',
  confirmation_code_is_incorrect: '認証コードが正しくありません。',
  please_re_enter_the_confirmation_code_that_was_sent_to_your_email:
    '再度ご入力してください。',
  please_sign_in_to_use_the_coupon: 'ログインしてください。',
  new_password: '新しいパスワード',
  confirm_password: 'パスワード確認',
  please_login_to_use: 'ログインしてください。',
  go_to_catalog: 'チラシページへ',
  view_on_map: '地図アプリを起動',
  call_now: '電話をかける',
  note: '店舗からのお知らせ',
  catalog_in_store: 'チラシ',
  coupon_detail: 'クーポン詳細',
  push_notification_detail: 'PUSH通知詳細',
  notification_detail: 'お知らせ詳細',
  register_member: '会員登録',
  once_time_per_day: '1日1回のみ',
  only_used_once: '1回のみ',
  day_off: '休日',
  work_time: '営業時間',
  detail_store: '店舗詳細',
  time: '有効期限',
  use: '利用可能回数',
  shop: '店舗',
  used_coupon: 'used coupon',
  local: 'Local',
  password_has_minimum_8_characters:
    'パスワードは英字と数字を組み合わせ、8文字以上で入力してください。',
  zip_code: '郵便番号',
  date_work: '営業日',
  date_off: '休日',
  birth_day: '生年月日',
  gender: '性別',
  job: '職業',
  status_of_residence: '同居家族形態',
  advanced: 'Advanced',
  no_by_empty: '必須項目です。',
  zip_code_has_minimum_7_number: 'Z - 郵便番号は7桁以上です。',
  please_select_a_time_less_than_the_current_time:
    ' - 現在の日付より小さい日付を選択してください。',
  sub_email: 'サブメール',
  email_and_sub_email_can_not_be_duplicated:
    'メールとサブメールが重複することはできません。',
  sub_email_already_exits: 'サブメールが存在しました。',
  type_zip_code: '郵便番号のフォーマットは数字でXXX-XXXXです。',
  type_password:
    'パスワードは英字と数字を組み合わせ、8文字以上で入力してください。',
  need_enable_permission: 'need enable permission',
  need_enable_enable_location:
    'あなたの位置情報へのアクセスを常に許可している場合は、位置情報に連動した、最新のお得情報をお届けします。アクセスをApp使用中のみ許可にしている場合は、Appを開いた時のみ更新のためすぐにお得情報が届かない場合があります。',
  need_enable_location_android_rejected:
    'あなたの位置情報へのアクセスを常に許可している場合は、位置情報に連動した、最新のお得情報をお届けします。アクセスをApp使用中のみ許可にしている場合は、Appを開いた時のみ更新のためすぐにお得情報が届かない場合があります。アプリの設定画面から変更をお願いします。',
  permission: '位置情報有効設定',
  need_enable_notification:
    '通知方法はテキスト、サウンド、アイコンバッジが利用できる可能性があります。通知方法は”設定”で設定できます。',
  status_network_error: 'インターネット接続が不安定です。',
  status_system_overload:
    'ただいまサーバが大変混み合っています。しばらく時間をおいてから、アクセスしてください。',
  got_cha: 'Gotcha', //TODO: translate to japanese
  congratulation: 'おめでとうございます !!', //TODO: translate to japanese
  reward_description: 'This is your Prize', //TODO: translate to japanese
  go_to_coupon: 'Go to coupon', //TODO: translate to japanese
  join_event: 'Join Event',
  scan_qr: 'QR読み取り',
  countless_time: '期間中何度でも利用可能',
  my_gotcha: 'My Gotcha',
  get_started_aplication: 'アプリをはじめる',
  my_gocha: 'ガチャ獲得済みクーポン',
  goto_mygotcha: 'ガチャ獲得済みクーポンへ',
  gotcha_reaward: '当たりクーポン例',
  gacha: 'ガチャ',
  starttime: '対象期間: ',
  time_use: '対象期間:',
  got_cha_detail: 'ガチャ詳細',
  events: 'スタンプラリー',
  scan_qrcode: 'QR読込',
  text_coupont: '特典を獲得する',
  can_choose_multi_reward:
    'スタンプラリーのスタンプ獲得数分クーポンへ交換することができます。',
  not_choose_multi_reward:
    'スタンプラリー目標達成でクーポンへ1度のみ交換ができます。',
  stamp: 'スタンプ',
  coupon_for_stamp: 'クーポン交換',
  congratulations: ' QR読み取り完了',
  description_congratulations:
    'スタンプを獲得しました。一覧から獲得状況をご確認ください。',
  continue: '続ける',
  text_qr_scann: '既にQR コードを読み取りました。',
  not_scann: 'NOT_SCAN_YET',
  scann: 'CORRECT_STAMP',
  flase_sann: 'WRONG_STAMP',
  can_choose: 'CAN_CHOOSE',
  choose: 'SELECTED',
  not_canchoose: 'NOT_ENOUGH_STAMP',
  textGoMyPage: '会員証を表示する',
  textGoMyCoupon: 'クーポンを見る',
  my_point: '保有ポイント',
  menu: 'メニュー',
  version: 'バージョン',
  maintail:
    'ただいまメンテナンス中の為、ご利用いただけません。しばらく待ってから再度ご利用いただけますようお願いいたします。',
  save: '保存する',
  please_enter_an_user_name_and_password:
    'ユーザーID及びパスワードを入力してください。  ',
  save_account_succsess: 'アカウント情報を保存しました。  ',
  need_enable_camera_with_setting_android:
    '店頭POPやチラシに掲載のQRコードを読み取り、マイルやクーポンに交換するために使用します。アプリの設定画面から変更をお願いします。',
  need_enable_camera:
    '店頭やチラシに掲載のQRコードを読み取り、マイルやクーポンに交換するために使用します。',
  error_text_input_username: '施設コードを入力してください。',
  question: 'よくあるご質問',
  error_text_input_password: 'システム利用コードを入力してください。',
  update_info_mypage_success: '変更が完了しました。',
  wrong_pass_mypage: 'パスワードは正しくありません。',
};
