export default {
  idPatientCode: "idPatientCode",
  idName: "idName",
  idHeight: "idHeight",
  idWeight: "idWeight",
  idIdCard: "idIdCard",
  idAddress: "idAddress",
  idDateBirthday: "idDateBirthday",
  ShowPoupRelationship: "ShowPoupRelationship",
  Gender: "gender",
  idPhone: "idPhone",
  idEmail: "idEmail",
  ShowChooseArea: "ShowChooseArea",
  ShowChooseAvatar: "ShowChooseAvatar",
};
