export const COLOR_BROWN = "#693013";
export const COLOR_BLACK = "#2A2A2A";
export const COLOR_GRAY = "#7D7D7D";
export const COLOR_BORDER = "#707070";
export const COLOR_WHITE = "#FFFFFF";
export const COLOR_GRAY_LIGHT = "#F2F2F2";
export const COLOR_GRAY_COUPON_USED = "#E0E0E0";
export const COLOR_RED_LIGHT = "#D94343";
export const COLOR_RED = "#D94343";
export const COLOR_GREEN = "#56AF45";
export const COLOR_VIOLET = "#c730c7";
export const COLOR_BLUE = "#1B32FF";
export const COLOR_BLUE_LIGHT = "#4C68D9";
export const COLOR_ORANGE = "#EC7105";
export const COLOR_YELLOW = "#ECBE05";
export const COLOR_YELLOW_LIGHT = "#FCEDCB";
export const COLOR_GRAY_300 = "#E0E0E0";
export const COLOR_GRAY_900 = "#656565";
export const COLOR_GREEN_LIGHT = "#56AF4520";
export const COLOR_PINK_LIGHT = "#FBEFEF";
export const COLOR_GREEN_RECORDS = "#06B050";
export const COLOR_BACKGROUND_RECORDS = "#E4E4E4";

const COLOR_TEXT = COLOR_BLACK;

const COLOR_TEXT_BUTTON_TYPE_1 = COLOR_WHITE;
const COLOR_BORDER_BUTTON_TYPE_1 = COLOR_ORANGE;

const COLOR_TEXT_BUTTON_TYPE_2 = COLOR_ORANGE;
const COLOR_BORDER_BUTTON_TYPE_2 = COLOR_ORANGE;

const COLOR_TEXT_TAB_BAR_ACTIVE = COLOR_WHITE;
const COLOR_BORDER_TAB_BAR_ACTIVE = COLOR_ORANGE;

const COLOR_TEXT_TAB_BAR_UN_ACTIVE = COLOR_ORANGE;
const COLOR_BORDER_TAB_BAR_UN_ACTIVE = COLOR_ORANGE;

export const APP_COLOR = {
  COLOR_TEXT,
  COLOR_TEXT_BUTTON_TYPE_1,
  COLOR_BORDER_BUTTON_TYPE_1,
  COLOR_TEXT_BUTTON_TYPE_2,
  COLOR_BORDER_BUTTON_TYPE_2,
  COLOR_TEXT_TAB_BAR_ACTIVE,
  COLOR_BORDER_TAB_BAR_ACTIVE,
  COLOR_TEXT_TAB_BAR_UN_ACTIVE,
  COLOR_BORDER_TAB_BAR_UN_ACTIVE,
  BACKGROUND_COLOR: COLOR_WHITE,
  COLOR_GRAY_LIGHT,
};
