import { Platform, StyleSheet } from "react-native";
import {
  Dimension,
  Colors,
  Fonts,
  SCREEN_WIDTH,
  fontsValue,
} from "../../../commons";

export default StyleSheet.create({
  styleContent: {
    backgroundColor: "white",
    paddingHorizontal: Dimension.padding2x,
    paddingBottom: Dimension.padding3x,
  },
  stList: {
    marginTop: Dimension.margin2x,
    flex: 1,
    // paddingBottom:40,
    marginBottom: 20
    // marginBottom: fontsValue(100),
  },
  lineSeparator: {
    height: Dimension.margin2x,
  },
  stContentEmpty: {
    justifyContent: "center",
    marginTop: Dimension.margin2x,
  },
  stImageEmpty: {
    // marginTop: -56,
    width: fontsValue(SCREEN_WIDTH - 100),
    height: fontsValue(SCREEN_WIDTH - 100),
    alignSelf: "center",
  },
  stTextTitleEmpty: {
    textAlign: "center",
    fontSize: Dimension.fontSize18,
    fontFamily: Fonts.SFProDisplaySemibold,
    color: Colors.colorTextMenu,
    letterSpacing: 0.5,
    lineHeight: 27,
    marginVertical: Dimension.margin2x,
    // marginTop: -18,
  },
  stTextContentEmpty: {
    textAlign: "center",
    fontSize: Dimension.fontSize14,
    fontFamily: Fonts.SFProDisplayRegular,
    color: Colors.textLabel,
    letterSpacing: 0.5,
    lineHeight: fontsValue(24),
    marginBottom: Dimension.margin2x,
  },
  stInputRow: {
    // flex: 1,
    marginTop: Dimension.margin4x,
    borderWidth: 0,
    borderBottomColor: Colors.colorBg2,
    borderBottomWidth: 1,
    position: "relative",
  },
  stContentInput: {
    borderColor: Colors.colorBg2,
    borderWidth: 0,
  },
  textDisable: {
    color: Colors.colorText,
    fontSize: Dimension.fontSize16,
    fontFamily: Fonts.SFProDisplaySemibold,
    marginHorizontal: Dimension.margin5,
  },
  stInputReason: {
    marginTop: Dimension.margin4x,
    position: "relative",
    borderColor: Colors.colorBg2,
    borderWidth: 0.75,
  },
  stContainButton: {
    // height: Dimension.heightInputView,
    // width:'100%',

    flexDirection: "row",
    borderRadius: 8,
    flex: 1,
    width: '100%',
    // borderColor: Colors.colorBg2,
    // borderWidth: 0.2,
    backgroundColor: "white",
    paddingRight: 10,
    paddingLeft: 8,
    paddingVertical: 8,
    alignItems: "center",

    // shadowOpacity: 0.25,
    // shadowRadius: 5,
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowColor: "#000000",
    // elevation: 3,
  },
  stIcon: {
    height: Dimension.heightDefault,
    width: Dimension.heightDefault,
    backgroundColor: Colors.colorBtBack,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  stTextButton: {
    color: Colors.textLabel,
    fontSize: Dimension.fontSize14,
    fontFamily: Fonts.SFProDisplaySemibold,
    marginHorizontal: Dimension.margin5,
  },
  styleText: {
    fontSize: 14,
    color: Colors.colorText1,
    fontFamily: Fonts.SFProDisplayRegular,
  },
  stContainHeader: {
    marginTop: Dimension.margin2x,
    marginHorizontal: Dimension.margin2x,
    backgroundColor: "white",
  },
  stFeedback: {
    marginTop: Dimension.margin,
    marginBottom: 5,
    marginHorizontal: Dimension.margin2x,
    backgroundColor: "white",
    borderRadius: Dimension.radiusButton,
    padding: 10,
    // shadowOpacity: 0.25,
    // shadowRadius: 5,
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowColor: "#000000",
    // elevation: 3,
  },
  stContainBlock: {
    marginTop: Dimension.margin,
    marginBottom: 5,
    marginHorizontal: Dimension.margin2x,
    backgroundColor: "white",
    borderRadius: Dimension.radiusButton,
    padding: 10,
    // shadowOpacity: 0.25,
    // shadowRadius: 5,
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowColor: "#000000",
    // elevation: 3,
  },

  styleTextTopic: {
    fontSize: Dimension.fontSize16,
    color: Colors.colorTextMenu,
    fontFamily: Fonts.SFProDisplaySemibold,
    // lineHeight: fontsValue(18),
  },

  styleTextTitle: {
    fontSize: Dimension.fontSize16,
    color: Colors.colorTextMenu,
    fontFamily: Fonts.SFProDisplayRegular,
    lineHeight: fontsValue(18),
  },
  styleTextContent: {
    fontSize: Dimension.fontSize16,
    color: 'black',
    fontFamily: Fonts.SFProDisplayRegular,
    lineHeight: fontsValue(18),
    marginTop: Dimension.margin,
  },
  stTextTimeCreate: {
    marginTop: Dimension.margin,
    alignSelf: "flex-end",
    marginLeft: Dimension.margin5,
    fontSize: Dimension.fontSize12,
    fontFamily: Fonts.SFProDisplayRegular,
  },
  styleContentDetail: {
    // flex: 1,
    backgroundColor: "white",
    paddingBottom: Dimension.padding3x,
    marginBottom: Dimension.padding3x,
  },
  stButtonConfirm: {
    flexDirection: "row",
    borderRadius: fontsValue(Dimension.radius),
    flex: 1,
    borderColor: Colors.colorBg2,
    borderWidth: 0.2,
    backgroundColor: "white",
    padding: fontsValue(Dimension.padding),
    alignItems: "center",
    shadowOpacity: 0.25,
    shadowRadius: 1,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowColor: "#000000",
    elevation: 1,
  },
  textContent: {
    fontSize: Dimension.fontSize16,
    color: Colors.colorTitleScreen,
    fontFamily: Fonts.SFProDisplayRegular,
    lineHeight: fontsValue(18),
    marginTop: Dimension.margin,
    textAlign: "center",
  },
  viewModalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(52, 52, 52, 0.8)",
  },
  viewModalContent: {
    margin: 8,
    backgroundColor: "white",
    borderRadius: 20,
    paddingTop: 22,
    paddingHorizontal: 8,
    paddingBottom: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  textTitle: {
    marginBottom: 15,
    textAlign: "center",
    fontSize: 20,
    fontFamily: "SFProText-Regular",
    color: "black",
  },
  viewCloseModal: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#00C6AD",
    marginTop: 46,
  },
  styleText: {
    color: '#00C6AD',
    fontFamily: Fonts.SFProDisplayRegular,
    fontSize: Dimension.fontSize18,
    marginLeft: 5
  },
  styleButtonSadAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
    flex: 1,
    marginBottom: 29
  },
  styleTextButtonSadAdd: {
    color: '#FF6F5B',
    fontFamily: Fonts.SFProDisplayRegular,
    fontSize: Dimension.fontSize16
  },
  // styleTextButtonSadAdd:{
  //   color:'#FF6F5B',
  //   fontFamily:Fonts.SFProDisplayRegular,
  //   fontSize:Dimension.fontSize16
  // },
  stIconSearch: {
    backgroundColor: Colors.colorBtBack,
    height: "100%",
    width: Platform.OS === "ios" ? 56 : 40,
  },

  stInput: {
    margin: Dimension.margin,
    // marginTop: Dimension.margin2x,
    borderRadius: Dimension.radiusButton,
    // borderBottomWidth: 1,
    // borderBottomColor: Colors.colorBg2,
  },
  styleContainInput: {
    height: fontsValue(46),
    borderRadius:fontsValue(16),
    backgroundColor:'#F8F8F8',
    borderColor:'white',
    marginHorizontal:Dimension.margin
  },
});
