export default Object.freeze({
  Avatar: 'avatar',
  FullName: 'fullName',
  DateOfBirth: 'dateOfBirth',
  Phone: 'phone',
  Email: 'email',
  Zalo: 'zalo',
  Facebook: 'facebook',
  BankName: 'bankName',
  BankAccount: 'bankAccount',
  BankAccountName: 'bankAccountName',
  cmnd1: 'cmnd1',
  cmnd2: 'cmnd2',
  Address: 'address',
  FullAddress: 'fullAddress',
  Area: 'Area',
  AreaFullName: 'areaFullName',
  Province: 'provinceId',
  District: 'districtId',
  Ward: 'wardId',
});
