export const STRING = {
    can_choose_multi_reward: 'スタンプラリーのスタンプ獲得数分クーポンへ交換することができます。',
    not_choose_multi_reward: 'スタンプラリー目標達成でクーポンへ1度のみ交換ができます。',
    coupon_for_stamp: 'クーポン交換',
    congratulations: ' QR読み取り完了',
    description_congratulations: 'スタンプを獲得しました。一覧から獲得状況をご確認ください。',
    continue: '続ける',
    stamp: 'スタンプ',
    scan_qrcode: 'QR読込',
    events: 'スタンプラリー',
    text_qr_scann: '既にQR コードを読み取りました。',
    text_qr_invalid: 'QRコードは無効です。',
    scan_qr: 'QR読み取り',
    an_error_occurred: '接続エラー',
    please_try_again_later: 'ただいま大変混み合っています。しばらく経ってから再度お試しください。',
    choose_answer: 'クイズの答えを選択してください。',
    quiz: 'クイズ',
    join_event: 'イベント詳細',
    time_use: '対象期間:',
    text_coupont: '特典を獲得する',
    text_usingstamp: '会計時にご注文のコーヒー数分のスタンプを獲得できま す。スタッフへアプリQRスタンプとお伝えください。読み込 み可能なQRコードをご提示します。',
    view_all: 'View all >>',
    are_you_sure_you_want_to_use_coupon: 'このクーポンを使用しますか。',
    cancel: 'キャンセル',
    ok: 'OK',
    notification: 'お知らせ',
    notificationEvent: 'あなたはイベントを完成しました。または、イベントが終了したので、どうぞイベントリストをご再確認ください。',
    email: 'メールアドレス',
    comfirm_email: 'Eメール確認',
    send: '送る',
    please_enter_your_email: '受賞するためにメールを入力してください。',
    use_coupon_email_success: 'メールをご送信しました。後程、ご受賞者の方にメールにて連絡いたします。',
    name: '氏名',
    year_old: '年令',
    zip_code: '郵便番号',
    men: '男達',
    women: '女性たち',
    address: '住所',
    tel: '連絡先',
    agree: '同意します',
    cannot_find_zip_code: '郵便番号が見つかりません',
    no_by_empty: '必須項目です。',
    city: '市区町村',
    district: '都道府県',
    apartmentNumber: '番地・号など',
    error_email_confirm: 'エラーメール確認',
    error_not_type_email: '有効なEメールアドレスを入力してください。',
    privacy_policy_agreement: 'プライバシーポリシー同意',
    click_here_for_details: '詳細はこちら',
    birth_day: '生年月日',
    please_review_the_information: '情報を確認してください',
    please_select_a_time_less_than_the_current_time: ' - 現在の日付より小さい日付を選択してください。',
    undefined: '未定義',
    please_login_to_use: 'ログインしてください。',
    userApply:'既に応募しました。',
    apply_success:'応募しました。',
    next:'次へ',
    checkFormApply:'入力した情報を確認してください。'

};
